from __future__ import annotations

META_OPTIMIZER_TEMPLATE_VERSION = 1

META_OPTIMIZER_LEARNING_RATE = 0.10
META_OPTIMIZER_WEIGHT_MIN = 0.05
META_OPTIMIZER_WEIGHT_MAX = 0.70
META_OPTIMIZER_UPDATE_INTERVAL = 5
META_OPTIMIZER_MIN_STABILITY = 0.50
META_OPTIMIZER_EXPLORATION_BOUND = 0.30