from __future__ import annotations

import allbrain.reducers as central
from allbrain import (
    adaptive_recovery,
    arbitration,
    attention,
    attribution,
    belief,
    calibration,
    capabilities,
    causal,
    contradiction,
    decision,
    dynamics,
    episodic,
    evidence,
    failure_memory,
    fusion,
    learning,
    learning_safety,
    meta_meta_scoring,
    meta_optimizer,
    meta_policy,
    meta_scoring,
    mitigation_learning,
    objective_system,
    policy_competition,
    policy_routing,
    predictive_failure,
    recovery_consensus,
    reputation,
    resilience,
    revision,
    routing,
    self_play,
    self_repair,
    semantic,
    soft_repair,
    telemetry,
    tradeoff_engine,
    value_alignment,
    workspace,
)

_PAIRS = [
    (central.AdaptiveRecoveryReducer, adaptive_recovery.AdaptiveRecoveryReducer),
    (central.RecoveryConsensusReducer, recovery_consensus.RecoveryConsensusReducer),
    (central.ResilienceReducer, resilience.ResilienceReducer),
    (central.SelfRepairReducer, self_repair.SelfRepairReducer),
    (central.SoftRepairReducer, soft_repair.SoftRepairReducer),
    (central.FailureMemoryReducer, failure_memory.FailureMemoryReducer),
    (central.MitigationLearningReducer, mitigation_learning.MitigationLearningReducer),
    (central.ArbitrationReducer, arbitration.ArbitrationReducer),
    (central.BeliefReducer, belief.BeliefReducer),
    (central.CalibrationReducer, calibration.CalibrationReducer),
    (central.ContradictionReducer, contradiction.ContradictionReducer),
    (central.DecisionReducer, decision.DecisionReducer),
    (central.ValueAlignmentReducer, value_alignment.ValueAlignmentReducer),
    (central.ObjectiveSystemReducer, objective_system.ObjectiveSystemReducer),
    (central.CapabilityLearningReducer, learning.CapabilityLearningReducer),
    (central.LearningSafetyReducer, learning_safety.LearningSafetyReducer),
    (central.MetaScoringReducer, meta_scoring.MetaScoringReducer),
    (central.MetaMetaScoringReducer, meta_meta_scoring.MetaMetaScoringReducer),
    (central.MetaOptimizerReducer, meta_optimizer.MetaOptimizerReducer),
    (central.MetaPolicyReducer, meta_policy.MetaPolicyReducer),
    (central.SelfPlayReducer, self_play.SelfPlayReducer),
    (central.CausalReducer, causal.CausalReducer),
    (central.EvidenceReducer, evidence.EvidenceReducer),
    (central.EpisodicReducer, episodic.EpisodicReducer),
    (central.SemanticReducer, semantic.SemanticReducer),
    (central.WorkspaceReducer, workspace.WorkspaceReducer),
    (central.TradeoffReducer, tradeoff_engine.TradeoffReducer),
    (central.TelemetryReducer, telemetry.TelemetryReducer),
    (central.ReputationReducer, reputation.ReputationReducer),
    (central.PolicyCompetitionReducer, policy_competition.PolicyCompetitionReducer),
    (central.PolicyRoutingReducer, policy_routing.PolicyRoutingReducer),
    (central.RoutingReducer, routing.RoutingReducer),
    (central.FusionReducer, fusion.FusionReducer),
    (central.AttentionReducer, attention.AttentionReducer),
    (central.AttributionReducer, attribution.AttributionReducer),
    (central.CapabilityReducer, capabilities.CapabilityReducer),
    (central.CapabilityDynamicsReducer, dynamics.CapabilityDynamicsReducer),
    (central.RevisionReducer, revision.RevisionReducer),
    (central.PredictiveFailureReducer, predictive_failure.PredictiveFailureReducer),
]


def test_central_reducers_are_domain_classes() -> None:
    for central_cls, domain_cls in _PAIRS:
        assert central_cls is domain_cls, f"{central_cls.__name__} is not domain identity"
